<?php
if(session_status()===PHP_SESSION_NONE){session_start();}
if(empty($_SESSION['admin_logged_in'])){header('Location: login.php');exit;}
require_once 'db.php'; require_once 'includes/case_service.php';
$admin=case_admin_identity(); case_run_escalations($pdo);
if(isset($_POST['mark_read'])){$pdo->prepare("UPDATE case_notifications SET read_at=NOW(),status='read' WHERE id=:id AND (recipient_id IS NULL OR recipient_id=:admin)")->execute(['id'=>(int)$_POST['mark_read'],'admin'=>$admin['id']]);header('Location: notifications.php');exit;}
$stmt=$pdo->prepare("SELECT n.*,g.tracking_token FROM case_notifications n JOIN grievances g ON g.id=n.grievance_id WHERE n.recipient_type='admin' AND (n.recipient_id IS NULL OR n.recipient_id=:admin) ORDER BY n.created_at DESC LIMIT 100");$stmt->execute(['admin'=>$admin['id']]);$items=$stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Case Notifications</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#fff8ef;color:#104911}.notice{border:1px solid rgba(84,140,47,.25);border-radius:14px;background:#fff8ef}.notice.unread{border-left:6px solid #ffd449;background:#fffdf2}</style></head><body><main class="container py-5" style="max-width:900px"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="fw-bold">Case notifications</h1><a class="btn btn-outline-success" href="dashboard.php">Dashboard</a></div><?php if(!$items):?><div class="alert alert-success">No notifications.</div><?php endif;?><?php foreach($items as $item):?><article class="notice <?=empty($item['read_at'])?'unread':''?> p-4 mb-3"><div class="d-flex justify-content-between gap-3"><div><div class="small fw-bold"><?=htmlspecialchars($item['tracking_token'])?></div><h2 class="h5 fw-bold"><?=htmlspecialchars($item['subject'])?></h2><p class="mb-1"><?=htmlspecialchars($item['body'])?></p><small><?=htmlspecialchars(date('M j, Y g:i A',strtotime($item['created_at'])))?></small></div><div><a class="btn btn-success btn-sm mb-2" href="view.php?id=<?=(int)$item['grievance_id']?>">Open</a><?php if(empty($item['read_at'])):?><form method="post"><button class="btn btn-outline-secondary btn-sm" name="mark_read" value="<?=(int)$item['id']?>">Mark read</button></form><?php endif;?></div></div></article><?php endforeach;?></main></body></html>
